name: NSHC
version: ${project.version}
main: me.towaha.nshc.NSHC
api-version: 1.13
authors: [Toaster, Nowaha]
description: A very origional survival gamemode

commands:
  nshcgamemanager:
    usage: /<command>
  nshcbossbar:
    usage: /<command>
  nshcscoreboard:
    usage: /<command>